server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls and redirects to the backend
    location /api/ {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
    }

    location ~ ^/[a-zA-Z0-9_-]\{7\}$ {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
    }
}
